name: Main Verify

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Lint
        run: deno lint AFPES.ts

      - name: Run Test
        run: deno test AFPES.ts

      - name: Run Check
        run: deno check AFPES.ts
